FROM fluxms/flux-eco-biotope:1.4.0 AS flux-eco-course-management
USER root

# Switch back to default user
COPY --chown=www-data:www-data ./app /app/
USER www-data
WORKDIR /app
#RUN composer install # --no-dev
EXPOSE 9501

ENV SWOOLE_HTTP_PORT=9501
ENV SWOOLE_HTTP_MESSAGE_RECEIVER_PORT=9502
ENV SWOOLE_HTTP_WORKER_NUM=10
ENV SWOOLE_HTTP_MAX_CONN=100
ENV SWOOLE_HTTP_MAX_REQUEST=500
ENV SWOOLE_HTTP_IPC_MODE=2
ENV SWOOLE_HTTP_TASK_WORKER_NUM=10
ENV SWOOLE_HTTP_TASK_IPC_MODE=2
ENV SWOOLE_HTTP_TASK_MAX_REQUEST=100
#Fixed Dispatch mode
ENV SWOOLE_HTTP_DISPATCH_MODE=2
ENV SWOOLE_HTTP_DAEMONIZE=0
ENV SWOOLE_HTTP_BACKLOG=2048
ENV SWOOLE_HTTP_OPEN_TCP_KEEPALIVE=1
ENV SWOOLE_HTTP_TCP_DEFER_ACCEPT=5
ENV SWOOLE_HTTP_OPEN_TCP_NODELAY=1
ENV SWOOLE_HTTP_LOG_FILE_PATH_NAME=/app/flux-app/logs/http.log

ENTRYPOINT ["sh", "docker_entrypoint.sh"]